Beamographic/rush

osu.Game.Rulesets.Rush.Tests/TestSceneMiniBoss.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBoss.cs

Probably missed case from https://github.com/swoolcock/rush/commit/3d22a77607e5026e9d8adf50118e9d62907bfa3d
Added a test case for making sure we potentially never hit this again. (and to start writing test scenes for each object :P)

Fix mini bosses potentially attacking before their start time

---

osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

Now uses the `GridContainer` for way better and easier dimension controlling, very damn useful to extend the height of the upcoming ground component right down to its parent height.

Refactor the structure of the playfield hierarchy

---

osu.Game.Rulesets.Rush.Tests/TestSceneGround.cs
osu.Game.Rulesets.Rush/UI/Ground/DefaultGround.cs
osu.Game.Rulesets.Rush/UI/Ground/GroundDisplay.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

Adds an initial implementation of the ground display component, compatible for skinning by providing a texture able to be adjacent with itself to perform the *infinite-scrolling* on (but to be hooked later on at skinning stage).
The default ground is currently a placeholder, simple written as an initial implementation:

Add initial implementation of the ground display

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHitPart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableNoteSheet.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableNoteSheetCap.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableNoteSheetTail.cs
osu.Game.Rulesets.Rush/UI/RushPlayerSprite.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

Ended up being various changes because they all touched similar areas:
* Fixed #20, hopefully.  Essentially made the jumping more lenient so that there's a 20% play height grace area before landing.  Also tweaked the jump/fall speeds to feel a little better.
* Fixed an issue where the dual hit was consuming actions too early and preventing jumps in front of a missed notesheet.
* Fixed an issue where a notesheet hold animation could sometimes be triggered even though the player missed the head.
* Fixed an issue where sawblade damage wasn't displaying.
* Fixed an issue where getting a great on a notesheet tail wouldn't correctly hide the cap.  Note that this actually exacerbates #13, as the player now explicitly gets a perfect if holding past the tail.
@frenzibyte I may self merge this one …

Fix jumping and various other visual glitches

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableNoteSheet.cs

Previously if you held down a notesheet's action before the head, it would count as breaking the notesheet but the hold star would stick to the current time.

Fix hold star sticking to player if the action is held too early

---

osu.Game.Rulesets.Rush.Tests/TestSceneMiniBoss.cs
osu.Game.Rulesets.Rush.Tests/TestSceneRushPlayer.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableHeart.cs
osu.Game.Rulesets.Rush/UI/HitTarget.cs
osu.Game.Rulesets.Rush/osu.Game.Rulesets.Rush.csproj

Closes #38 
Can't find the exact reason (will look through tomorrow), but my guess is that this is due to confliction with JIT stuff due to us using a very old package of osu!lazer. @swoolcock assigning you to check and merge this one, and publish a new release for this. (we should probably have dependabot set up to avoid issues like these)

Bump osu!lazer package to latest

---

osu.Game.Rulesets.Rush.Tests/osu.Game.Rulesets.Rush.Tests.csproj

Avoids receiving package bumps while we don't really need it.

Remove unnecessary package updating in tests project

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHitPart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableLanedHit.cs
osu.Game.Rulesets.Rush/UI/HitTarget.cs
osu.Game.Rulesets.Rush/UI/RushLanedPlayfield.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

Required for editor.
Closes #60

Move laned hit objects to nested playfields

---

osu.Game.Rulesets.Rush/Judgements/CollisionDamagingJudgement.cs
osu.Game.Rulesets.Rush/Judgements/HeartJudgement.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableHeart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableLanedHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBoss.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableRushHitObject.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableSawblade.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheet.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetHead.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetTail.cs

Enforces using `MinResult`/`MaxResult` instead of arbitrarily specifying a hit result value, fixes a crash when missing a heart object, due to applying result `HitResult.Miss` while the minimum hit result is `HitResult.IgnoreMiss`.
Not sure how to handle the case in `DrawableMiniBoss` though:
https://github.com/swoolcock/rush/blob/4ff68beb4599ef6067a4488778a6c0a6c1f8e11d/osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBoss.cs#L126-L132 (@swoolcock @LumpBloom7 any suggestions?)

Enforce using Min/Max result types instead of arbitrary values

---

.vscode/launch.json
.vscode/tasks.json

This PR provides some vscode specific tasks as a convenience for developers using vscode.
I copied and adapted the tasks from my own rulesets, which in turn was adapted from the main osu repo.

Add vscode tasks

---

osu.Game.Rulesets.Rush/Beatmaps/RushCraftedBeatmapConverter.cs
osu.Game.Rulesets.Rush/Beatmaps/RushGeneratedBeatmapConverter.cs
osu.Game.Rulesets.Rush/Objects/StarSheet.cs

Resolves #112 
Previously StarSheets will use `HitObject.Samples` regardless of the original std HitObject type, causing forced StarSheets to sound different from their originals. osu!standard sliders tend to have their hitsounding stored within `IHasRepeat.NodeSamples` so that the head, tail and possibly repeats get their own hitsounds.  
I have adjusted the StarSheet to use the NodeSample list when possible, and falling back to `original.Samples` (or the parameter) when that isn't possible.
Tested with the map shown in the original issue, along with some others.

Respect node samples of hitobjects on beatmap conversion

---

osu.Game.Rulesets.Rush/RushDifficultyCalculator.cs

We don't have any proper difficulty calculator, so all beatmaps are currently listed as 0 star maps and players have to guess relative difficulty. The standard SR values should give a decent enough approximation for now.

Add placeholder SR values

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheet.cs
osu.Game.Rulesets.Rush/Objects/StarSheet.cs

Previously star sheets provided 3 combos, one at the start, and two at the end. The judgement it gives is also the minimum between the two, causing overlap.

Fix star sheet bodies also being considered in acc and combo

---

.github/workflows/dotnet-core.yml
.vscode/launch.json
.vscode/tasks.json
osu.Game.Rulesets.Rush.Tests/osu.Game.Rulesets.Rush.Tests.csproj
osu.Game.Rulesets.Rush.sln
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/osu.Game.Rulesets.Rush.csproj

This is done for the sole reason of being able to load a development rush! build side by side with an official release build, for comparing things between pretty quickly and identify bugs without having to resort to exiting the game, switching to master, etc..
Builds generated by CI through artifacts now use a special configuration named `Development`, which is optimized like your usual release config, but falls down within the development builds.
- In the above image, the ruleset displayed description below the selector button is rather unfortunate, but can't be helped within our scope.

Distinguish rush! release builds from development builds

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHitPart.cs
osu.Game.Rulesets.Rush/Objects/DualHit.cs

As simple as it gets, though I did do some minor tweaks to shift input handling and result application responsibility to the DualHitParts, and made the parent do the bare minimum required.

Fix DualHits providing 3 judgements instead of two

---

osu.Game.Rulesets.Rush.Tests/Visual/TestSceneRushPlayer.cs
osu.Game.Rulesets.Rush/Beatmaps/RushGeneratedBeatmapConverter.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheet.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetCap.cs
osu.Game.Rulesets.Rush/Objects/StarSheet.cs

Temporarily fixing warnings caught by R# code inspector until we have a R# code inspector tool running in CI, just to get things working properly for me and get the habit of ignoring warnings on my IDE 😛
@swoolcock Requesting review for the changes done in `RushGeneratedBeatmapConverter`, not sure if you intentionally left them there, and whether you're fine with removing them for now until they become necessary later (not sure if we'll modify our generated converter much)

Fix warnings caught by R# code inspector

---

osu.Game.Rulesets.Rush.Tests/Replay/RushReplayFrameTest.cs
osu.Game.Rulesets.Rush/Replays/RushReplayFrame.cs
osu.Game.Rulesets.Rush/RushInputManager.cs
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/UI/DrawableRushRuleset.cs
osu.Game.Rulesets.Rush/UI/RushReplayRecorder.cs

Currently has to convert from and to legacy replay frames due to no modern replay encoding support osu!lazer-side yet, which limits tertiary and quaternary actions from being saved as-is in replays, but looks to be working as expected to for now.

Add replay recording support

---

osu.Game.Rulesets.Rush/RushRuleset.cs

By overriding the list of valid results in `RushRuleset`, we are able to prevent osu from listing all HitResults in the post-game score card.

Remove unused HitResults from results card

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHitPart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableHeart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableLanedHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBoss.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBossTick.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMinion.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableRushHitObject.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableRushJudgement.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableSawblade.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheet.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetCap.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetHead.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableStarSheetTail.cs
osu.Game.Rulesets.Rush/Objects/Drawables/IDrawableLanedHit.cs
osu.Game.Rulesets.Rush/Objects/Drawables/Pieces/HeartPiece.cs
osu.Game.Rulesets.Rush/Objects/Drawables/Pieces/MinionPiece.cs
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/UI/DefaultHitExplosion.cs
osu.Game.Rulesets.Rush/UI/DrawableRushRuleset.cs
osu.Game.Rulesets.Rush/UI/HealthText.cs
osu.Game.Rulesets.Rush/UI/HeartHitExplosion.cs
osu.Game.Rulesets.Rush/UI/LanePlayfield.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs
osu.Game.Rulesets.Rush/UI/StarSheetHitExplosion.cs

Resolves #59
Fixes #25 
I've made pooling work for each HitObject and nested HitObjects, along with explosions, judgements, and the health text. I tried to not touch anything irrelevant or do anything that I would consider out of scope for this PR.
~~Some objects and properties aren't lane agnostic, while most objects are fine in this regard, I find the anchor adjustments to be a bit ugly. `MinionPiece` also changes sprites based on the lane the DHO is in, and [I've made it so that it updates its animation set when the DHO has a new applied HitObject](https://github.com/LumpBloom7/rush/blob/4a3484334abd1418d2eec9ab77c0ba3ef35ca99c/osu.Game.Rulesets.Rush/Objects/Drawables/Pieces/MinionPiece.cs#L39). These issues, as mentioned earlier, could be completely alleviated with nested …

Pool HitObjects, explosions and judgements

---

osu.Game.Rulesets.Rush/Judgements/RushJudgement.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMiniBoss.cs
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/Scoring/HeartHitWindows.cs
osu.Game.Rulesets.Rush/Scoring/RushHitWindows.cs
osu.Game.Rulesets.Rush/Scoring/SawbladeHitWindows.cs

https://github.com/ppy/osu/pull/12294 reduced the value of PERFECT judgements down to 315 from 350. Because of this, GREAT judgements are now worth ~95% acc, up from ~85% making it way too easy to maintain a high acc even with many mistakes.
I've adjusted the judgements so that GREAT/GOOD is used instead, which are worth 300 and 200 respectively, and changes their acc values to 100%/66.6%. This does make it a tad harder to maintain a high acc when compared to our results before the judgement updates.
If we want to present these judgements as if they are PERFECT/GREAT to the player, we could consider changing what text the judgements show (`result.GetRushJudgementText()` ), and change what the scorecard shows by overriding `Ruleset.GetDisplayNameForResult()`.

Shift judgement range to GREAT/GOOD from PERFECT/GREAT

---

osu.Game.Rulesets.Rush/Objects/Drawables/DrawableDualHitPart.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableMinion.cs

As discussed [on discord](https://discord.com/channels/741467017923788900/825687815734951956/831157320116994068), the Minions and DualHitParts do not visibly react to players hitting them early. This makes it seem like they should still be hittable, while they are in fact not accepting nor blocking any input, causing a chain reaction of missed notes because the player keeps attempting to hit that note. It is what I believe is giving players the feeling that random misses are occuring, instead of it being the fault of HitWindows.
I've added a basic animation that plays whenever the object is missed, so that players are notified of their mistakes, and that they should adjust their timing. 
https://user-images.githubusercontent.com/12001167/115126063-b3958f00-9fcc-11eb-8427-544efa84e2a4.mp4

Add miss animations to Minions and DualHitParts

---

osu.Game.Rulesets.Rush/UI/Ground/GroundDisplay.cs
osu.Game.Rulesets.Rush/UI/HealthText.cs
osu.Game.Rulesets.Rush/UI/RushPlayerSprite.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

Fixes #27 as well.
Currently, a grid is used to specify regions for specific playfield elements to be. However, nearly all elements required further positional adjustments via `anchors`, `origins`, `position`, and `padding`, with some of them having a parent container with even more adjustments. This makes it harder to immediately tell where a playfield element would be, when looking at the properties, since they would be inheriting several layers of properties from parents and grandparents. (It can reach a depth of 5+ containers!)
This PR removes the use of the grid, and reducing the number of parents that can affect positioning of the playfield elements. Most of the positional adjustments are now isolated within the individual playfield elements themselves, rather than being spread out. …

Simplify the way playfield elements are positioned

---

osu.Game.Rulesets.Rush/Mods/RushModFlashlight.cs
osu.Game.Rulesets.Rush/Mods/RushModPerfect.cs
osu.Game.Rulesets.Rush/Mods/RushModSuddenDeath.cs
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/UI/RushPlayfield.cs

This PR adds 5 mods, Flashlight, Perfect, Sudden Death, Wind Up, and Wind Down.
- Flashlight - larger size than other modes (to cover two lanes) and gets smaller when >100 combos and >200 combos.
- Perfect, Sudden Death, Wind Up, and Wind Down has the same effect as other modes.
Flashlight size/location:
Flashlight: https://www.youtube.com/watch?v=X1I1C3IMEPc
Wind Up: https://www.youtube.com/watch?v=oNAT1dYG3g8

Add FL, PF, SD, Wind Up, Wind Down

---

osu.Game.Rulesets.Rush/Configuration/FeverActivationMode.cs
osu.Game.Rulesets.Rush/Configuration/RushRulesetConfigManager.cs
osu.Game.Rulesets.Rush/Configurations/RushRulesetConfigManager.cs
osu.Game.Rulesets.Rush/Objects/Drawables/DrawableFeverBonus.cs
osu.Game.Rulesets.Rush/Replays/RushAutoGenerator.cs
osu.Game.Rulesets.Rush/Replays/RushFramedReplayInputHandler.cs
osu.Game.Rulesets.Rush/Replays/RushReplayFrame.cs
osu.Game.Rulesets.Rush/RushInputManager.cs
osu.Game.Rulesets.Rush/RushRuleset.cs
osu.Game.Rulesets.Rush/UI/DrawableRushRuleset.cs
osu.Game.Rulesets.Rush/UI/Fever/FeverProcessor.cs
osu.Game.Rulesets.Rush/UI/RushReplayRecorder.cs
osu.Game.Rulesets.Rush/UI/RushSettingsSubsection.cs

This PR introduces an option to enable automatic fever activation, which is on by default.
When it is on, fever will be activated when a result causes the progress to fill to 100%, using the `TryActivateFever` method.
`ReplayButtonState.Smoke` has been repurposed to store the auto fever setting, and is used to ensure that replays will use the settings set at the time of recording, so as to prevent desyncs. The `UsingAutoFever` state provided by `RushFramedInputHandler` will always take priority if a replay is active.
`FeverProcessor` uses `DrawableRushRuleset.UsingAutoFever` in order to determine whether it should automatically trigger fever, and has no knowledge of whether a replay is active or not. (`DrawableRushRulset.UsingAutoFever` already prioritizes replays)

Implement automatic fever activation

---

osu.Game.Rulesets.Rush/UI/Ground/DefaultGround.cs
osu.Game.Rulesets.Rush/UI/Ground/GroundDisplay.cs

Previously, `DefaultGround` loaded a tonne of lines for the platform, this is to ensure that the ground is long enough that it will not cut off on wider monitors. However, having a whole bunch of lines added to the FillFlowContainer is very wasteful, when most of it is never seen.
This PR makes it so that the slats are added/removed based on draw size invalidations, and no more is added than the bare minimum required to cover the width of the playfield.
This also fixes the random jitter that occurs every now and then, since we are using the exact slat spacing for the illusion rather than using `ground.DrawSize.X/2` as an approximation.

Optimize DefaultGround

---

osu.Game.Rulesets.Rush/UI/HitTarget.cs

Previously when beating, it scaled from the top-left corner rather than the centre. This fixes that.
<sub> This likely regressed in #150 </sub>

Fix HitTargets animations having the wrong origin

---

osu.Game.Rulesets.Rush.Tests/Visual/TestSceneTouchInputHandling.cs
osu.Game.Rulesets.Rush/osu.Game.Rulesets.Rush.csproj

Resolves build issues with current versions of osu!lazer as osu.Game (and others) now targets .NET Core 6.
As far as testing goes (tested on an iOS build with this ruleset + 2 other custom rulesets), no problems have arisen from this change.
Also bumps ppy.osu.Game to the latest release (2023.419.0) as of the time of writing.

Switch to .NET 6
